# Don't show anything too noisy
add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "🌱 "
style = "bold purple"

[git_status]
style = "bold yellow"

[nodejs]
symbol = "⬢ "
style = "bold green"

[time]
disabled = false
format = '[$time]($style) '
time_format = "%H:%M"
style = "bold dimmed white"
